services:
  postgres:
    image: postgres:16
    container_name: database_bakers_bill
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
      PGTZ: ${PGTZ}
    ports:
      - "5431:5432"
    volumes:
      - db_data_bakers_bill:/var/lib/postgresql/data
      
  
volumes:
  db_data_bakers_bill:
